apiVersion: v1
kind: Service
metadata:
  name: quad9-doh
  labels:
    name: quad9-doh
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  selector:
    app: quad9-doh
